apiVersion: v1
kind: Service
metadata:
  name: gateway-backstage
  namespace: gateway-backstage
  labels:
    app: gateway-backstage
    managed-by: backstage
    type: gateway
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: gateway-backstage
